POST http://localhost:8080/events
content-type:application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlQGdtYWlsLmNvbSIsInVzZXJJZCI6MX0.Wz-thZmQkviXBPOgi0W0HNFXVOVSBgSuXRthZibO6LM

{
    "name": "Test event 3",
    "description": "A test event", 
    "location": "A test location",
    "dateTime": "2026-01-01T15:30:00.000Z"
}