POST http://localhost:8080/events
content-type:application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RlMUBnbWFpbC5jb20iLCJleHAiOjE3ODkzMjYwODAsInVzZXJJZCI6MX0.oV8pjTye8Kv3cxHBweRj6WTlUMPbmaxcq4003xE-O60

{
    "name": "Test event 5",
    "description": "A test event", 
    "location": "A test location",
    "dateTime": "2026-01-01T15:30:00.000Z"
}